### ISSUE TITLE
Bot Is Not Playing Music

### ISSUE THREAD

**Issue by DayyanK** [GreenBotDeveloppement/Green-bot#101]
I am using green bot open source code but when I am trying to play music in it it's showing now playing and song name and then directly shows queue conclude and also when I am trying to use skip command it's showing error I am attaching the screenshot. 

Thanks. 
![IMG_20220615_150546](https://user-images.githubusercontent.com/83121326/173796625-a73417e9-1e43-44e7-b2a3-d744f487bc45.jpg)

**Comment by pauldb09** [comment]
Consider using the dev branch to have it fixed
