### ISSUE TITLE
prefix command doesnt work 

### ISSUE THREAD

**Issue by RyanWilliams99** [GreenBotDeveloppement/Green-bot#172]
**Describe the bug**
when i try to use the *prefix command it gives me "This command is not available anymore to encourage people to use slash command! All bots will stop answering to commands with a prefix like this one!"

**To Reproduce**
1. use the prefix command
2. see error

**Expected behavior**
it would change the prefix 

**Screenshots**
![image](https://user-images.githubusercontent.com/34068116/191811856-df792dec-77a9-4a60-a8ec-5c89339d591f.png)

**Version**
Please give these versions:
NodeJs:
Green-bot;

**Additional context**

**Comment by pauldb09** [comment]
Yeah it has been removed because discord want's all bots to switch to slash commands
