### ISSUE TITLE
Le code s'arrête quand il n'y a pas d'arguments derrière la commande.

### ISSUE THREAD

**Issue by mewzax** [GreenBotDeveloppement/Green-bot#46]
J'ai un problème,
le système de traduction stoppe le code avec cette erreur quand on ne rentre pas d'arguments (dans les commandes avec arguments)
ex: *g-start donne:
Uncaught Error: Translate: Params error: Unknow text ID or missing text

Voilà, Merci d'avance

**Comment by pauldb09** [comment]
Bonjour @slowwdev
 cette erreur n'est pas due au fait qu'il n'y ait pas d'arguments mais c'est une erreur de traduction.
Pouvez vous envoyer l'erreur en entier ? 
J'ai mit à jour les traductions. Essayez de tester avec les nouvells

**Comment by slowwdev** [comment]
Ah par contre le bug se reproduit avec avec la commande 8ball
