### ISSUE TITLE
Code qui ferme quand .backup create

### ISSUE THREAD

**Issue by slowwdev** [GreenBotDeveloppement/Green-bot#47]
Bonjour, je rencontre beaucoup d'erreurs avec le bot, beaucoup sont dus aux emojis, mais cela, je parviens un peu près à les gérer.
Mon nouveau problème est la commande .backup create
Je reçois l'erreur "Uncaught TypeError: message.guild.channels.cache.sort(...).array is not a function"
Pouvez-vous m'aider s'il vous plaît ?

**Comment by slowwdev** [comment]
J'ai aussi beaucoup d'erreurs de traduction. Existe t-il une version sûre, sans aucun bugs ?

**Comment by skyfra** [comment]
Hello @slowwdev ! 

Tu pourrais nous envoyer un petit screen de l'erreur entière pour les problèmes de backup ?

Merci d'avance
