### ISSUE TITLE
Default volume not working when using the controller

### ISSUE THREAD

**Issue by cattaneod** [GreenBotDeveloppement/Green-bot#60]
**Describe the bug**
When the queue is created using the controller, the initialVolume is set to 60 instead of the default volume set by the user.

This can be fixed by replacing `initialVolume: 60` with `initialVolume: guildDB.defaultVolume` in `events/discord/messageCreate.js#L103`

**Comment by pauldb09** [comment]
Yes. I will fix it soon 👍🏼 Thanks for the report
