### ISSUE TITLE
Prefix not changing 

### ISSUE THREAD

**Issue by BajrangDalLeader** [GreenBotDeveloppement/Green-bot#66]
I changed prefix in config.js from * to Ri! but it still is replying to old prefix only and youtube alerts commands is not working

**Comment by pauldb09** [comment]
Hello @BajrangDalLeader ! For the prefix issue, it has been fixed in [2098f8c](https://github.com/GreenBotDeveloppement/Green-bot/commit/2098f8cb0c0ad33a6aad2a531fb86e55bd8d3e8a) So just do *setprefix ri! in your server . Could you provide more informations for the youtube alert command?

**Comment by BajrangDalLeader** [comment]
I also found more errors commands which require you to type enable and disable do not work such as boost-message , anti-dc and many more and when you use command *help [any command] status always is ✅ even if it the command is not enabled
