### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by SpaceLeft** [GreenBotDeveloppement/Green-bot#67]
![Capture](https://user-images.githubusercontent.com/40790870/154795022-74756a72-a8e4-4a3b-8bdd-ad9ecd3c7d7a.PNG)

**Comment by SpaceLeft** [comment]
@pauldb09

**Comment by pauldb09** [comment]
Try to down grade to mongodb v5.3

**Comment by SpaceLeft** [comment]
@pauldb09, please help me.

**Comment by SpaceLeft** [comment]
@pauldb09

**Comment by PNB01** [comment]
@pauldb09 was this solved? Seems like they were left on read a little bit. Lol.

**Comment by JoniXTech** [comment]
@SpaceLeft Just read the error and do it
